image: docker:latest
services:
  - docker:dind

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 
  DOCKER_HOST: "tcp://docker:2375"


before_script:
  - cd ReCollect/
  - apk add --no-cache python py2-pip
  - pip install --no-cache-dir docker-compose==1.12.0
  - docker-compose -v

stages:
  - build
  - test
  - deploy

compile:
  image: maven:3.3-jdk-8-alpine
  stage: build
  script:
    - chmod +x script.sh
    - ./script.sh
    - mvn clean compile

unit_test:
  stage: test
  script:
    - mvn clean test -B

package:
  stage: deploy
  script:
    - mvn package

