image: docker:latest
services:
  - docker:dind

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 

before_script:
  - cd ReCollect/

stages:
  - build
  - test
  - deploy

compile:
  image: maven:3.3-jdk-8-alpine
  stage: build
  script:
    - apt-get install docker-ce docker-ce-cli containerd.io
    - docker-compose up -d
    - mvn clean compile

unit_test:
  stage: test
  script:
    - mvn clean test -B

package:
  stage: deploy
  script:
    - mvn package

