image: docker:latest

services:
- docker:dind
- maven
- mysql:5.7

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  SPRING_DATASOURCE_URL: jdbc:mysql://localhost/reCollect?createDatabaseIfNotExist=true&serverTimezone=Europe/London&useSSL=false
  MYSQL_DATABASE: "reCollect"
  MYSQL_USER: "adminrc"
  MYSQL_PASSWORD: "admin"
  MYSQL_ROOT_PASSWORD: "admin"
    
before_script:
  - cd ReCollect/

stages:
  - connect
  - build
  - test
  - package
  - deploy

  variables:
    DOCKER_DRIVER: overlay2

connect:
  stage: connect
  tags:
    - docker
  services:
    - mysql:5.7
  before_script:
    - sudo apt install -y mysql-client
    - sudo apt install -y mysql-server
    - mysql --version
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" "${MYSQL_DATABASE}"

build:
  image: maven
  stage: build
  tags:
    - docker
  services:
    - mysql:5.7
  script:
    - mvn clean compile

test:
  image: maven
  stage: test
  tags:
    - docker
  services:
    - mysql:5.7
  script:
    - mvn clean test -Dtest=\!\*SeleniumTest

package:
  image: maven
  tags:
    - docker
  stage: package
  services:
    - mysql:5.7
  script:
    - mvn clean package -Dtest=\!\*SeleniumTest
    - ls 
    - ls target
  artifacts:
    paths:
      - ReCollect/target/*.jar

deploy:
  image: docker
  stage: deploy
  tags:
    - docker
  services:
    - mysql:5.7
    - docker:dind
    - maven
  only:
    - master
    - cd
  script:
    #- sudo apt update
    #- sudo apt upgrade -y
    #- sudo apt install -y py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    #- pip install docker-compose
    #- docker-compose down
    - docker-compose up -d --build


sonarcloud-check:
  image: maven:3.6.3-jdk-11
  variables:
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify -DskipTests sonar:sonar 
  only:
    - merge_requests
    - master


