image: openjdk:11-stretch

services:
  - mysql:latest

variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 
  DOCKER_HOST: "tcp://docker:2375"
  MYSQL_DATABASE: 'reCollect'
  MYSQL_USER: 'adminrc'
  MYSQL_PASSWORD: 'admin'
  MYSQL_ROOT_PASSWORD: 'password'

before_script:
  - cd ReCollect/

stages:
  - build
  - test
  - deploy

compile:
  image: maven:3.3-jdk-8-alpine
  stage: build
  script:
    - mvn clean compile

unit_test:
  image: maven:3.3-jdk-8-alpine
  stage: test
  script:
    - sleep 60
    - mvn clean test

package:
  image: maven:3.3-jdk-8-alpine
  stage: deploy
  script:
    - sleep 60 
    - mvn package

