image: docker:latest

services:
- docker:dind
- maven
- mysql:5.7

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  # GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql/reCollect?createDatabaseIfNotExist=true&serverTimezone=Europe/London&useSSL=false
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
    
before_script:
  - cd ReCollect/

stages:
  - connect
  - build
  - test
  - package
  - deploy

connect:
  stage: connect
  tags:
    - docker
  variables:
    MYSQL_DATABASE: "reCollect"
    MYSQL_USER: "adminrc"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root"
  services:
    - mysql:5.7
  before_script:
    - apk --no-cache add mysql-client
    - mysql --version
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"

build:
  image: maven
  stage: build
  tags:
    - docker
  variables:
    MYSQL_DATABASE: "reCollect"
    MYSQL_USER: "adminrc"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root"
  services:
    - mysql:5.7
  script:
    - mvn clean compile

test:
  image: maven
  stage: test
  tags:
    - docker
  variables:
    MYSQL_DATABASE: "reCollect"
    MYSQL_USER: "adminrc"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root"
  services:
    - mysql:5.7
  script:
    - mvn clean test -Dtest=\!\*SeleniumTest

package:
  image: maven
  tags:
    - docker
  stage: package
  variables:
    MYSQL_DATABASE: "reCollect"
    MYSQL_USER: "adminrc"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root"
  services:
    - mysql:5.7
  script:
    - mvn clean package -Dtest=\!\*SeleniumTest
  artifacts:
    paths:
      - ./target/*.jar

deploy:
  image: docker
  stage: deploy
  tags:
    - docker
  variables:
    MYSQL_DATABASE: "reCollect"
    MYSQL_USER: "adminrc"
    MYSQL_PASSWORD: "admin"
    MYSQL_ROOT_PASSWORD: "root"
  services:
    - mysql:5.7
    - docker:dind
    - maven
  only:
    - master
    - cd
  script:
    - apk update
    - apk upgrade
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose up -d --build


sonarcloud-check:
  image: maven:3.6.3-jdk-11
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify -DskipTests sonar:sonar 
  only:
    - merge_requests
    - master
  variables:
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

