image: maven:3.3-jdk-8-alpine


variables: 
  MAVEN_OPTS: "-Dmaven.repo.local=.m2" 

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  script:
    - mvn clean compile

unit_test:
  stage: test
  script:
    - mvn clean test -B

package:
  stage: deploy
  script:
    - mvn package

